name: AWS Lambda Zip Deploy - Python
author: Qubitro
description: Zip deploy to AWS Lambda with requirements in a separate layer.
inputs:
  aws_region:
    description: the AWS region where your lambdas are located
    required: true
  requirements_txt:
    description: the name/path to the requirements.txt file
    required: true
    default: 'requirements.txt'
  pip_layer_arn:
    description: The ARN for the Lambda layer the dependencies should be pushed to without the version (every push is a new version).
    required: true
  custom_layer_1_path:
    description: the path to the code for custom layer 1
  custom_layer_1_arn:
    description: the ARN for custom layer 1
  custom_layer_2_path:
    description: the path to the code for custom layer 2
  custom_layer_2_arn:
    description: the ARN for custom layer 2
  custom_layer_3_path:
    description: the path to the code for custom layer 3
  custom_layer_3_arn:
    description: the ARN for custom layer 3
  custom_layer_4_path:
    description: the path to the code for custom layer 4
  custom_layer_4_arn:
    description: the ARN for custom layer 4
  public_layer_1_arn:
    description: the ARN for public layer 1
  public_layer_2_arn:
    description: the ARN for public layer 2
  public_layer_3_arn:
    description: the ARN for public layer 3
  public_layer_4_arn:
    description: the ARN for public layer 4
  lambda_function_names:
    description: The Lambda function names (comma-separated if you have multiple). Check the AWS docs/readme for examples.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws_region }}
    - ${{ inputs.requirements_txt }}
    - ${{ inputs.lambda_function_names }}
    - ${{ inputs.pip_layer_arn }}
    - ${{ inputs.custom_layer_1_path }}
    - ${{ inputs.custom_layer_1_arn }}
    - ${{ inputs.custom_layer_2_path }}
    - ${{ inputs.custom_layer_2_arn }}
    - ${{ inputs.custom_layer_3_path }}
    - ${{ inputs.custom_layer_3_arn }}
    - ${{ inputs.custom_layer_4_path }}
    - ${{ inputs.custom_layer_4_arn }}
    - ${{ inputs.public_layer_1_arn }}
    - ${{ inputs.public_layer_2_arn }}
    - ${{ inputs.public_layer_3_arn }}
    - ${{ inputs.public_layer_4_arn }}
branding:
  icon: 'cloud-lightning'
  color: 'white'
